version: '3.7'
services:

  # The Application
  debian-base:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: Sistema-yourClientName
    volumes:
      - ./home/:/home/
    stdin_open: true
    tty: true
    restart: always
    hostname: yourClientName
    environment:
      - DEBIAN_FRONTEND=noninteractive
      - DEBCONF_NONINTERACTIVE_SEEN=true
      - DEBIAN_PRIORITY=critical
      - DEBCONF_PRIORITY=critical
